config/routes.rb
Filippas::Application.routes.draw do



    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :user do
      get '/login' => 'devise/sessions#new'
      get '/logout' => 'devise/sessions#destroy'
    end
    resources :token_authentications, :only => [:create, :destroy]
    resources :users
    resources :surveys
    
    namespace :user do
      root :to => "dashboard#userprofile"
    end
        match '/dashboard' => 'dashboard#userprofile', :as => 'user_root'
        match 'user/dashboard', :to => 'dashboard#userprofile'
        match '/userprofile', :to => 'dashboard#userprofile'
        match '/surveys', :to => 'dashboard#userprofile'
        match '/surveys/coupon', :to => 'surveys#coupon'
        match '/surveys/new', :to => 'surveys#new'
        match '/surveys/:id/coupon', :to => 'surveys#coupon'
        match '/contact', :to => 'pages#contact'
        match '/about',   :to => 'pages#about'
        match '/help',    :to => 'pages#help'
        match '/savetoexcel.php',    :to => 'pages#savetoexcel.php'
        match '/privacy', :to => 'pages#privacy'
        match '/hours', :to => 'pages#hours'
        match '/carryout', :to => 'pages#carryout'
        match '/restaurant',   :to => 'pages#restaurant'
        match '/banquets',    :to => 'pages#banquets'
        match '/catering', :to => 'pages#catering'
        match '/events',   :to => 'pages#events'
        match '/blog',    :to => 'pages#blog'
        match '/contact', :to => 'pages#contact'
        match '/gallery', :to => 'pages#gallery'
        match '/aboutthechef', :to => 'pages#aboutthechef'
        match '/charities', :to => 'pages#charities'
        match '/winestore', :to => 'pages#winestore'
        match '/emailclub', :to => 'pages#emailclub'
        match '/happyhour', :to => 'pages#happyhour'
        match '/holidays', :to => 'pages#holidays'
        match '/menu', :to => 'menu#index'
        match '/restaurant_menu', :to => 'menu#restaurant_menu'
        match '/catering_menu', :to => 'menu#catering_menu'
        match '/banquets_menu', :to => 'menu#banquets_menu'
        root :to => 'pages#home'
    end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def userprofile
    @users = User.all.excludes(:id => current_user.id)
    @surveys = Survey.all.excludes(:id => current_user.id)
    @survey = Survey.new(params[:survey])
    @title = "User Profile"
  end
  
end 

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/userprofile.html.erb
<script> 
$(function() {
	$( "#tabs" ).tabs();
});
</script>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

<p><%= link_to "Take Customer Survey", surveys_new_path %></p>
 <p><%= link_to "Edit User Profile", edit_user_registration_path %></p>

<% if user_signed_in? %>
	 <% if can? :manage, @users %>
<h1>Admin Controls</h1>
<div id="tabs"> 
	<ul> 
	<li><a href="#tabs-1">Users </a></li>
      <li><a href="#tabs-2">Survey </a></li>
		<li><a href="#tabs-3">Menus</a></li>
	<li><a href="#tabs-4">Events</a></li>

      
	</ul> 
   <div id="tabs-1">

		<table>
		  <thead>
		    <tr>
				<th></th>
				<th>User</th>
				<th>Email</th>
				<th>Birthday</th>
				<th>Gender</th>
				<th>Newsletter</th>
				<th>Role</th>
		    </tr>
		  </thead>
		  <tbody>
		  	 <% for user in @users %>
			    <tr>
					<td><%= link_to "Edit", edit_user_path(user) %> | <%= link_to "Delete", user, :confirm => "Are you sure?", :method => :delete %></td>
					<td><%= user.first_name %> <%= user.last_name %>  </td>
					<td><%= user.email %>  </td>
					<td><%= user.birthday %>  </td> 
					<td><%= user.gender %>  </td>
					<td><%= user.newsletter %>  </td>
					<td><%= user.role %>  </td>
			    </tr>
		  </tbody>  
		<% end %>
		</table>

	</p>
   </div>

   <div id="tabs-2">

	<table>
	  <thead>
	    <tr>
			<th></th>
				<th>Name</th>
				<th>Coupon Code</th>
				<th>Visit Date</th>
			<th>Check Number</th>
	    </tr>
	  </thead>
	  <tbody>

	      <% for survey in @surveys %>
	    <tr>
	     <td><%= link_to "Destroy", survey, :confirm => 'Are you sure?', :method => :delete %></td>
	<td><%= survey.first_name %>&nbsp;<%= survey.last_name %></td>
		 <td><%= survey.id %></td>
		<td><%=  survey.visit_month %>/<%=  survey.visit_day %>/<%=  survey.visit_year %> </td>	   
		<td><%=  survey.check_number %> </td>
	    </tr>
	    <% end %>
	  </tbody>  
	</table>
   </div>

	<div id="tabs-3"> 
		<p>add menu</p> 
	</div> 
	<div id="tabs-4">
		   <p>add event</p>

	   </div>
</div>

  <% end %>
 
<% end %>