config/routes.rb
Filippas::Application.routes.draw do



    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :user do
      get '/login' => 'devise/sessions#new'
      get '/logout' => 'devise/sessions#destroy'
    end
    resources :token_authentications, :only => [:create, :destroy]
    resources :users
    resources :surveys
    
    namespace :user do
      root :to => "dashboard#userprofile"
    end
        match '/dashboard' => 'dashboard#userprofile', :as => 'user_root'
        match 'user/dashboard', :to => 'dashboard#userprofile'
        match '/userprofile', :to => 'dashboard#userprofile'
        match '/surveys', :to => 'dashboard#userprofile'
        match '/surveys/coupon', :to => 'surveys#coupon'
        match '/surveys/new', :to => 'surveys#new'
        match '/surveys/:id/coupon', :to => 'surveys#coupon'
        match '/contact', :to => 'pages#contact'
        match '/about',   :to => 'pages#about'
        match '/help',    :to => 'pages#help'
        match '/savetoexcel.php',    :to => 'pages#savetoexcel.php'
        match '/privacy', :to => 'pages#privacy'
        match '/hours', :to => 'pages#hours'
        match '/carryout', :to => 'pages#carryout'
        match '/restaurant',   :to => 'pages#restaurant'
        match '/banquets',    :to => 'pages#banquets'
        match '/catering', :to => 'pages#catering'
        match '/events',   :to => 'pages#events'
        match '/blog',    :to => 'pages#blog'
        match '/contact', :to => 'pages#contact'
        match '/gallery', :to => 'pages#gallery'
        match '/aboutthechef', :to => 'pages#aboutthechef'
        match '/charities', :to => 'pages#charities'
        match '/winestore', :to => 'pages#winestore'
        match '/emailclub', :to => 'pages#emailclub'
        match '/happyhour', :to => 'pages#happyhour'
        match '/holidays', :to => 'pages#holidays'
        match '/menu', :to => 'menu#index'
        match '/restaurant_menu', :to => 'menu#restaurant_menu'
        match '/catering_menu', :to => 'menu#catering_menu'
        match '/banquets_menu', :to => 'menu#banquets_menu'
        root :to => 'pages#home'
    end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :first_name 
  field :last_name
  field :email
  field :role
  field :newsletter
  field :phone_number
  field :encrypted_password, :limit => 128, :default => "", :null => false
  field :password_salt, :default => "", :null => false
  field :reset_password_token
  field :remember_token
  field :remember_created_at, :type => DateTime
  field :sign_in_count, :type => Integer, :default => 0
  field :current_sign_in_at, :type => DateTime
  field :last_sign_in_at, :type => DateTime
  field :current_sign_in_ip
  field :last_sign_in_ip 
  field :facebook_uid
  field :facebook_token
  field :location_name
  field :location_id
  field :birthday, :type => DateTime
  field :gender
  
  ROLES = %w[admin user]
  
  validates_presence_of :first_name, :last_name, :email
  validates_uniqueness_of :email, :case_sensitive => false
  attr_accessible :first_name, :last_name, :email, :role, :password, :password_confirmation, :remember_me
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def show
      @user = User.find(params[:id])
      @title = @user.first_name
    end
  
  def index
    @users = User.excludes(:id => current_user.id)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to userprofile_path
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated User."
      redirect_to userprofile_path
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to userprofile_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 50 })
      gravatar_image_tag(user.email.downcase, :alt => user.name,
                                              :class => 'gravatar',
                                              :gravatar => options)
    end
end

app/views/users/_form.html.erb
<p><%= f.label :first_name %><br />
<%= f.text_field :first_name %></p>

<p><%= f.label :last_name %><br />
<%= f.text_field :last_name %></p>

<p><%= f.label :email %><br />
<%= f.text_field :email %></p>

<p><%= f.label :password %><br />
<%= f.password_field :password %></p>

<p><%= f.label :password_confirmation %><br />
<%= f.password_field :password_confirmation %></p>

<% if can? :manage, @users %>
<p><%= f.label :role %>: <%= f.collection_select :role, User::ROLES, :to_s, :humanize, {:include_blank => true} %></p>
<% end %>

<p><%= f.submit "Submit" %></p>

app/views/users/edit.html.erb
<%= form_for @user, :url => user_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, :url => user_index_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p></p>
<p>User: <%= @user.last_name %> <%= @user.first_name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Role:<%= @user.role %></p>
<% if can? :manage, @users %>
	Hello Admin!
	<% end %>
	
	
	<table class="profile" summary="Profile information">
	  <tr>
	    <td class="main">
	      <h1>
	 
	        <%= @user.first_name %> <%= @user.last_name %>
	      </h1>
	    </td>
	    <td class="sidebar round">
	      <strong>Name</strong> <%= @user.first_name %> <%= @user.last_name %><br />
	      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
	    </td>
	  </tr>
	</table>  